'use client'
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCart";
import { useState } from "react";

const outfit = Outfit({ subsets: ["latin"]  });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname()
  const showHeader = params==='/sign-in'|| params === '/create-account'? false:true
  const [updateCart, setUpdateCart] = useState(false)
  return (
    <html lang="en">
      <body className={outfit.className}>
        <UpdateCartContext.Provider value={{ updateCart, setUpdateCart }}>
          {showHeader && <Header />}
          <Toaster />
          {children}
          <Footer />
        </UpdateCartContext.Provider>
      </body>
    </html>
  );
}
